# Generated by Django 3.2.20 on 2023-07-11 23:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=4)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
                ('fname', models.CharField(default='', max_length=55)),
                ('date_of_birth', models.DateField(max_length=datetime.datetime.now)),
                ('adress', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default='1')),
                ('adress', models.CharField(default='', max_length=212)),
                ('info', models.JSONField()),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=68)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='ParentsModel',
            fields=[
                ('personmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kundalik.personmodel')),
                ('user_name', models.CharField(default='', max_length=66)),
                ('password', models.CharField(default='', max_length=44)),
            ],
            options={
                'db_table': 'parent',
            },
            bases=('kundalik.personmodel',),
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('personmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kundalik.personmodel')),
                ('toifa', models.CharField(choices=[('Ol', "Oliy Ma'lumotli"), ('OR', "O'rta Ma'lumotli"), ('PE', "O'qtituvchi Pedagok")], default='', max_length=2)),
                ('salary', models.PositiveIntegerField(default=1)),
                ('school', models.ManyToManyField(to='kundalik.SchoolModel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundalik.subjectmodel')),
            ],
            bases=('kundalik.personmodel',),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('personmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kundalik.personmodel')),
                ('user_name', models.CharField(default='', max_length=55)),
                ('password', models.BooleanField(default=False)),
                ('activate', models.BooleanField(default=False)),
                ('phone', models.CharField(default='', max_length=15)),
                ('clasS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.classmodel')),
                ('parents', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.parentsmodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundalik.schoolmodel')),
            ],
            options={
                'db_table': 'student',
            },
            bases=('kundalik.personmodel',),
        ),
        migrations.CreateModel(
            name='Grademodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('mark', models.PositiveSmallIntegerField(default=1)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.subjectmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundalik.studentmodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.teachermodel')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.subjectmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundalik.studentmodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.teachermodel')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
