# Generated by Django 3.2.20 on 2023-07-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=4)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default='1')),
                ('adress', models.CharField(default='', max_length=212)),
                ('info', models.JSONField()),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
